---
name: update available modules

on:
  workflow_call:
    inputs: 
      config-path:
        required: true
        type: string

jobs:
  stub:
    runs-on: ubuntu-latest
    steps:
      - name: print message
        run: | 
          echo "hello i am working"
      - name: print current repo
        run: |      
            echo "Current directory (PWD): $PWD"
            echo "GitHub workspace directory: $GITHUB_WORKSPACE"
